name: Deployment Check (Delayed)

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 7 minutes
        run: sleep 420  # 7 minutes = 420 seconds
        
      - name: Check website availability
        run: |
          response=$(wget -qO- https://wappenraten.tvluke.de/)
          if echo "$response" | grep -q "Quellcode verfügbar"; then
            echo "Website is up and contains the expected string"
            exit 0
          else
            echo "Website check failed"
            exit 1
          fi